### PR TITLE
Better forge and fabric seperation

### PR DESCRIPTION
**Pull request by MrRedstoneToGo**
This pull request improves the recipe management in this mod.

By the way, Fabric is still loading the forge recipes because it doesn't know the forge's loading conditions. I fixed that as well.

### CODE REVIEW

**Comment by AstralOrdana** [comment]
im fairly certain that moonlight lib makes it so the forge recipe conditions can be read by fabric, though splitting the data files between the branches makes sense, I forgot you could do that

**Comment by AstralOrdana** [comment]
this is all very clean though, thank you so much for the pr

**Comment by BugInYourCode01** [comment]
Items related to vanilla have an empty condition but who cares.

**Comment by BugInYourCode01** [comment]
I used GitHubs find and replace. It's very practical

**Comment by AstralOrdana** [comment]
you used `fabric:all_mods_loaded` in places and looking into fabric's resource conditions, it appears there's also a `fabric:any_mods_loaded` but when trying to actually use that one in the mod, the recipe fails to load, are you familiar with this system enough to know why that might be?

**Comment by BugInYourCode01** [comment]
Where did you see that there is `fabric:any_mods_loaded`? I just took the load conditions from Create Fabric.
Alternatively, try writing the alternative mods in the array of `fabric:load_conditions` as a second condition. Maybe this will work as desired.

**Pull request merged**
